### ISSUE TITLE
Initial commit

### ISSUE THREAD

**Issue by rafamizes** [dartoos-dev/json_cache#1]
Push to this repository the project skeleton with basic configurations.

**Comment by 0pdd** [comment]
@rafamizes 3 puzzles [#2](https://github.com/dartoos-dev/json_cache/issues/2), [#3](https://github.com/dartoos-dev/json_cache/issues/3), [#4](https://github.com/dartoos-dev/json_cache/issues/4) are still not solved.

**Comment by 0pdd** [comment]
@rafamizes 2 puzzles [#3](https://github.com/dartoos-dev/json_cache/issues/3), [#4](https://github.com/dartoos-dev/json_cache/issues/4) are still not solved; solved: [#2](https://github.com/dartoos-dev/json_cache/issues/2).

**Comment by 0pdd** [comment]
@rafamizes all 3 puzzles are solved here: [#2](https://github.com/dartoos-dev/json_cache/issues/2), [#3](https://github.com/dartoos-dev/json_cache/issues/3), [#4](https://github.com/dartoos-dev/json_cache/issues/4).
