### ISSUE TITLE
Minor improvement in the README introduction section

### ISSUE THREAD

**Issue by rafamizes** [dartoos-dev/json_cache#10]
The text part about the api should be placed under the "Getting Started" section.

**Comment by 0pdd** [comment]
@rafamizes the puzzle [#12](https://github.com/dartoos-dev/json_cache/issues/12) is still not solved.

**Comment by 0pdd** [comment]
@rafamizes the only puzzle [#12](https://github.com/dartoos-dev/json_cache/issues/12) is solved here.
