### ISSUE TITLE
List all keys 

### ISSUE THREAD

**Issue by Ai-Kiwi** [dartoos-dev/json_cache#152]
Is there a way to list all keys? If not one should be created as this would allow for scanning over all cached data and seeing if it has been expired yet.

**Comment by rafamizes** [comment]
Hello,

There is currently no way to list all keys used in the cache. However, I loved your idea. Therefore, I will implement a method like "Future<List<String>> keys()" to obtain all the keys as soon as possible.

**Comment by Ai-Kiwi** [comment]
> Hello,
> 
> Currently, there is no way to list all keys used in the cache. However, I loved your idea. Therefore, as soon as possible, I will implement a method like `Future<List<String>> keys()` to get all keys.

That sounds great it will help tons with my project. Thank you.

**Comment by rafamizes** [comment]
@Ai-Kiwi ,
First of all, thanks for opening this issue.

I want to let you know that I've just released `JsonCache 4.0.0` that, among other improvements, contains your suggested feature: list all keys — via method `keys`.

Check it out.

**Comment by Ai-Kiwi** [comment]
> @Ai-Kiwi ,
> First of all, thanks for opening this issue.
> 
> I want to let you know that I've just released  [JsonCache 4.0.0](https://pub.dev/packages/json_cache) that, among other improvements, implements your suggestion: list all keys — via method `keys`.
> 
> Check it out.
> 
> Cheers!

Thank you so much. I will definitely look into using it when i get a chance.
