### ISSUE TITLE
Async operations don't complete inside testWidgets()

### ISSUE THREAD

**Issue by markstory** [dartoos-dev/json_cache#72]
I'm working on my first flutter application, so I may have missed an obvious solution to this. I'm running into problems interacting with json_cache + localstorage within the context of tests.  I've attempted to create a minimal reprodction.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:json_cache/json_cache.dart';
import 'package:localstorage/localstorage.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('database insert', (tester) async {
    final LocalStorage storage = LocalStorage('test-idea');
    var database = JsonCacheMem(JsonCacheLocalStorage(storage));
    print('before');
    await database.refresh('test', {'k': 'v'});
    print('set value');
  });
}
```

When I run this test with `flutter test` it prints `before` but never prints `set value`. However, if I use `test()` instead of `testWidgets()` the test completes successfully. The broader context of what I'm trying to do is, write a more complex test case where I display a form. That form contains dropdown menus that contain data that would be read from `json_cache`, but I'm not currently able to get data into `json_cache`.

**Comment by markstory** [comment]
I did some more poking around and found that storing data into json_cache works fine if I do it in `setUp()`. Is it best to avoid writing data inside `testWidgets()`?

**Comment by markstory** [comment]
> First of all, thanks for opening this issue.

You're welcome :heart: Thank you for putting this library together, I've been loving it so far.

**Comment by rafamizes** [comment]
Hi again.

It all boils down to a [race condition](https://stackoverflow.com/questions/34510/what-is-a-race-condition) with the testWidgets method that is causing a [deadlock](https://en.wikipedia.org/wiki/Deadlock) inside Localstorage. All you need to do to fix this is to run your test code inside a `tester.runAsync` method.

For your particular case, the unit test code should look like this:

```dart
testWidgets('database insert', (WidgetTester tester) async {
  tester.runAsync(() async {
    print('before');
    await database.refresh('test', <String, dynamic>{'k': 'v'});
    print('set value');
  });
});
```
Please let me know if the previous tip worked so that I can close this issue.

Regards.

**Comment by markstory** [comment]
@rafamizes Yes, using `runAsync()` to update localstorage works perfectly. Thank you so much.
